#!/bin/bash
set -ex

# ignore any option; we're just a fake yum-builddep.
if [ -n "$1" ] ; then
   [[ "$1" =~ ^- ]] && shift
fi

TARGET=$(readlink -f $1)
case $1 in
    *.src.rpm)
        pushd $(mktemp -d)
        rpm2cpio $TARGET | cpio -iv --make-directories '*.spec'
        BUILDREQUIRES=$(/tmp/parse-spec-build-requires.pl $(ls *.spec))
        popd
        ;;
    *.spec)
        BUILDREQUIRES=$(/tmp/parse-spec-build-requires.pl $TARGET)
        ;;
    *)
        echo "unrecognized extension in filename $TARGET"
        exit 1
        ;;
esac
SHOULDINSTALL=""
for v in ${BUILDREQUIRES}
do
    { yum info ${v} > /dev/null && PACKAGE=${v} ; } || PACKAGE=$(repoquery --arch=$(arch) --whatprovides ${v})
    SHOULDINSTALL="${SHOULDINSTALL} ${PACKAGE}"
done
SHOULDINSTALL=$(echo -n ${SHOULDINSTALL} | sed -e 's/^ *//' -e 's/ *$//')
{ [ -n "${SHOULDINSTALL}" ] && yum install $SHOULDINSTALL ; } || /bin/true
