#!/bin/bash
set -ex
BUILDREQUIRES=$(/tmp/parse-spec-build-requires.pl $1)
SHOULDINSTALL=""
for v in ${BUILDREQUIRES}
do
    PACKAGE=$(repoquery --arch=$(arch) --whatprovides ${v} | head -n 1)
    SHOULDINSTALL="${SHOULDINSTALL} ${PACKAGE}"
done
SHOULDINSTALL=$(echo -n ${SHOULDINSTALL} | sed -e 's/^ *//' -e 's/ *$//')
{ [ -n "${SHOULDINSTALL}" ] && yum install $SHOULDINSTALL ; } || /bin/true
