#!/usr/bin/env python
import sys
import os
from commands import getstatusoutput
from tempfile import NamedTemporaryFile

forward_args = []
filename = None
for arg in sys.argv[1:]:
    if arg.startswith("-"):
        forward_args.append(arg)
    else:
        filename = arg
        break

if filename is None:
    raise ValueError, "could not find filename in parameters"

if filename.endswith(".src.rpm"):
    # just forward
    status, output = getstatusoutput("/usr/bin/yum-builddep.real %s %s" % (" ".join(forward_args), filename))
    if status != 0:
	    print output
    	sys.exit(1)
    sys.exit(0)

lines = open(filename).readlines()
nosources =  [line for line in lines if (not line.startswith("Source") and not line.startswith("Patch") and not "%setup" in line)]

out = NamedTemporaryFile()
out.write("".join(nosources))
out.flush()

status, output = getstatusoutput("/usr/bin/rpmbuild --nodeps -bs %s" % out.name)
if status != 0:
	print output
	sys.exit(1)

srpm = output.replace("Wrote: ", "").strip()
# we aren't doing a proper sanification of what's forwarded to yum-builddep, let's hope we don't need it.
status, output = getstatusoutput("/usr/bin/yum-builddep.real %s %s" % (" ".join(forward_args), srpm))
if status != 0:
	print output
	sys.exit(1)

os.unlink(srpm)
